language: python
sudo: true
python:
  - "2.7"
install:
  - pip install ansible
before_script:
  - ansible --version
  - sh ./test/before_script.sh
script:
  - ansible-playbook --syntax-check ./test/travis-ci-site.yml -i ./test/hosts
  - ansible-playbook ./test/travis-ci-site.yml -i ./test/hosts
  - sh ./test/test.sh
