---
# tasks file for djyugg.nodebrew

- name: check installed nodebrew
  command: which nodebrew
  ignore_errors: True
  register: nodebrew_installed

- name: install nodebrew
  shell: curl -L git.io/nodebrew | perl - setup
  sudo_user: "{{ nodebrew.install_user }}"
  when: nodebrew_installed|failed

- name: put nodebrew path setting script
  template: src=nodebrew.sh.j2 dest=/etc/profile.d/nodebrew.sh owner=root group=root mode=0755
  sudo: true
  when: nodebrew_installed|failed

- name: check installed node.js
  command: which node
  ignore_errors: True
  register: nodejs_installed

- name: check installed node.js version
  command: nodebrew ls | grep {{ nodebrew.nodejs_version }}
  ignore_errors: True
  when: nodejs_installed|failed
  register: nodejs_target_version_exist

- name: install node.js
  shell: $SHELL -lc "nodebrew install-binary {{ nodebrew.nodejs_version }}"
  sudo: true
  sudo_user: "{{ nodebrew.install_user }}"
  when: nodejs_target_version_exist|failed

- name: select node.js version
  shell: $SHELL -lc "nodebrew use {{ nodebrew.nodejs_version }}"
  sudo: true
  sudo_user: "{{ nodebrew.install_user }}"
  when: nodejs_target_version_exist|failed
