---
# tasks file for djyugg.nodebrew

- name: install nodebrew
  shell: curl -L git.io/nodebrew | perl - setup
  sudo_user: "{{ nodebrew.install_user }}"

- name: put nodebrew path setting script
  template: src=nodebrew.sh.j2 dest=/etc/profile.d/nodebrew.sh owner=root group=root mode=0755
  sudo: true

- name: install node.js
  shell: $SHELL -lc "nodebrew install-binary {{ nodebrew.nodejs_version }}"
  sudo: true
  sudo_user: "{{ nodebrew.install_user }}"

- name: select node.js version
  shell: $SHELL -lc "nodebrew use {{ nodebrew.nodejs_version }}"
  sudo: true
  sudo_user: "{{ nodebrew.install_user }}"
